// Auto-generated by Supabase from the live schema. Do not edit by hand.
// Regenerate with: supabase gen types typescript --project-id cjflwpcxfprxxjbhjxlo
// Owner: @DanteDia

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      conversations: {
        Row: {
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          audio_url: string | null
          content: string
          conversation_id: string
          created_at: string
          id: string
          role: string
        }
        Insert: {
          audio_url?: string | null
          content: string
          conversation_id: string
          created_at?: string
          id?: string
          role: string
        }
        Update: {
          audio_url?: string | null
          content?: string
          conversation_id?: string
          created_at?: string
          id?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string
          equipment_available: string[]
          fitness_level: string
          goals: string[]
          id: string
          injuries: string[]
          onboarding_completed: boolean
          tenant_id: string
          training_days_per_week: number
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          equipment_available?: string[]
          fitness_level?: string
          goals?: string[]
          id: string
          injuries?: string[]
          onboarding_completed?: boolean
          tenant_id: string
          training_days_per_week?: number
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          equipment_available?: string[]
          fitness_level?: string
          goals?: string[]
          id?: string
          injuries?: string[]
          onboarding_completed?: boolean
          tenant_id?: string
          training_days_per_week?: number
        }
        Relationships: [
          {
            foreignKeyName: "profiles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      routine_days: {
        Row: {
          created_at: string
          day_of_week: number
          id: string
          label: string
          muscle_groups: string[]
          routine_id: string
        }
        Insert: {
          created_at?: string
          day_of_week: number
          id?: string
          label?: string
          muscle_groups?: string[]
          routine_id: string
        }
        Update: {
          created_at?: string
          day_of_week?: number
          id?: string
          label?: string
          muscle_groups?: string[]
          routine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "routine_days_routine_id_fkey"
            columns: ["routine_id"]
            isOneToOne: false
            referencedRelation: "routines"
            referencedColumns: ["id"]
          },
        ]
      }
      routine_exercises: {
        Row: {
          ai_reasoning: string | null
          completed: boolean
          created_at: string
          exercise_name: string
          id: string
          notes: string | null
          order_index: number
          reps: number
          rest_seconds: number
          routine_day_id: string
          sets: number
          weight_kg: number | null
        }
        Insert: {
          ai_reasoning?: string | null
          completed?: boolean
          created_at?: string
          exercise_name: string
          id?: string
          notes?: string | null
          order_index?: number
          reps?: number
          rest_seconds?: number
          routine_day_id: string
          sets?: number
          weight_kg?: number | null
        }
        Update: {
          ai_reasoning?: string | null
          completed?: boolean
          created_at?: string
          exercise_name?: string
          id?: string
          notes?: string | null
          order_index?: number
          reps?: number
          rest_seconds?: number
          routine_day_id?: string
          sets?: number
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "routine_exercises_routine_day_id_fkey"
            columns: ["routine_day_id"]
            isOneToOne: false
            referencedRelation: "routine_days"
            referencedColumns: ["id"]
          },
        ]
      }
      routines: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          name: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "routines_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          created_at: string
          id: string
          logo_url: string | null
          name: string
          primary_color: string
          secondary_color: string
          slug: string
        }
        Insert: {
          created_at?: string
          id?: string
          logo_url?: string | null
          name: string
          primary_color?: string
          secondary_color?: string
          slug: string
        }
        Update: {
          created_at?: string
          id?: string
          logo_url?: string | null
          name?: string
          primary_color?: string
          secondary_color?: string
          slug?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
